# config.yaml
workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
  replicaCount: 1
  containerSpec:
    imageUri: CONTAINER_URI
    env:
    - name: BUCKET
      value: "MY_BUCKET"
    - name: LB_API_SECRET_NAME
      value: "MY_SECRET"
